'use client';

import { useEffect, useMemo, useState } from 'react';
import { useActivityRealtime } from '@/hooks/useActivityRealtime';

type Metric={code:string;name:string;unit:string;direction:'UP_IS_BETTER'|'DOWN_IS_BETTER'};
type Target={behavior:string;successMeasure:string;evidence:string;firstAction:string;supportNeeded:string};
type Feed={
 activity:{id:string;title:string;status:string};
 metrics:Metric[];
 plan:null|{id:string;startDate:string;reviewD7:string;reviewD14:string;reviewD30:string;status:string;targets:Array<{sequence:number;behavior:string;elements:any}>};
 metricRows:Array<{code:string;baseline:number|null;day30:number|null;percentChange:number|null;improved:boolean|null}>;
};

const blankTarget=():Target=>({behavior:'',successMeasure:'',evidence:'',firstAction:'',supportNeeded:''});

export default function ThirtyDayPlanParticipant({activityId}:{activityId:string}){
 const[feed,setFeed]=useState<Feed|null>(null);const[startDate,setStartDate]=useState(()=>new Date().toISOString().slice(0,10));const[targets,setTargets]=useState<Target[]>([blankTarget(),blankTarget(),blankTarget()]);const[baselines,setBaselines]=useState<Record<string,string>>({});const[initialized,setInitialized]=useState(false);const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/activities/'+activityId+'/thirty-day-plan',{cache:'no-store'});const d=await r.json();if(r.ok){setFeed(d);if(!initialized){if(d.plan){setStartDate(String(d.plan.startDate).slice(0,10));setTargets((d.plan.targets||[]).map((t:any)=>({behavior:t.behavior,successMeasure:t.elements?.successMeasure||'',evidence:t.elements?.evidence||'',firstAction:t.elements?.firstAction||'',supportNeeded:t.elements?.supportNeeded||''})).slice(0,3));}const map:Record<string,string>={};for(const m of d.metricRows||[])if(m.baseline!==null&&m.baseline!==undefined)map[m.code]=String(m.baseline);setBaselines(map);setInitialized(true)}}else setMsg(d.error||'Gagal memuat 30-Day Plan')}
 useEffect(()=>{void load()},[activityId,initialized]);
 useActivityRealtime(activityId,load,5000);
 const valid=useMemo(()=>targets.length===3&&targets.every(t=>t.behavior.trim().length>=5&&t.successMeasure.trim().length>=3&&t.evidence.trim().length>=3&&t.firstAction.trim().length>=3),[targets]);
 async function submit(){setBusy(true);setMsg('');const numeric=Object.fromEntries(Object.entries(baselines).map(([k,v])=>[k,v.trim()===''?null:Number(v)]));const r=await fetch('/api/activities/'+activityId+'/thirty-day-plan',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({startDate,targets,baselines:numeric})});const d=await r.json();setBusy(false);if(!r.ok){setMsg(d.error||'Gagal menyimpan 30-Day Plan');return;}setMsg('Plan tersimpan. Review D+7, D+14, dan D+30 sudah dihitung'+(d.managerMapped?' dan manager sudah terpetakan.':' — manager belum terpetakan.'));await load()}
 if(!feed)return <div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm text-slate-600">{msg||'Memuat 30-Day Plan…'}</div>;
 return <div className="mt-4 space-y-5">
   <div className="rounded-2xl bg-slate-950 p-4 text-white"><div className="text-xs font-bold uppercase tracking-[.18em] text-amber-300">30-Day Action Plan</div><p className="mt-2 text-sm leading-6 text-slate-300">Tetapkan 3 target perilaku yang observable, bukti keberhasilan, dan baseline impact metric agar review D+7/D+14/D+30 terukur.</p></div>
   <label className="block text-sm font-semibold text-navy">Tanggal mulai<input disabled={feed.activity.status!=='OPEN'} type="date" value={startDate} onChange={e=>setStartDate(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label>
   <div className="space-y-4">{targets.map((t,i)=><div key={i} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="font-semibold text-navy">Target {i+1}</div><label className="mt-3 block text-sm">Behavior<textarea disabled={feed.activity.status!=='OPEN'} value={t.behavior} onChange={e=>setTargets(targets.map((x,j)=>j===i?{...x,behavior:e.target.value}:x))} placeholder="Perilaku spesifik yang akan diubah/dibangun" className="mt-1 min-h-20 w-full rounded-xl border border-slate-300 px-3 py-2"/></label><label className="mt-3 block text-sm">Success measure<input disabled={feed.activity.status!=='OPEN'} value={t.successMeasure} onChange={e=>setTargets(targets.map((x,j)=>j===i?{...x,successMeasure:e.target.value}:x))} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2"/></label><label className="mt-3 block text-sm">Evidence of done<input disabled={feed.activity.status!=='OPEN'} value={t.evidence} onChange={e=>setTargets(targets.map((x,j)=>j===i?{...x,evidence:e.target.value}:x))} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2"/></label><label className="mt-3 block text-sm">First action<input disabled={feed.activity.status!=='OPEN'} value={t.firstAction} onChange={e=>setTargets(targets.map((x,j)=>j===i?{...x,firstAction:e.target.value}:x))} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2"/></label><label className="mt-3 block text-sm">Support needed<input disabled={feed.activity.status!=='OPEN'} value={t.supportNeeded} onChange={e=>setTargets(targets.map((x,j)=>j===i?{...x,supportNeeded:e.target.value}:x))} placeholder="Opsional" className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2"/></label></div>)}</div>
   <div className="rounded-2xl border border-slate-200 bg-white p-4"><div className="font-semibold text-navy">Impact Metrics — Baseline</div><p className="mt-1 text-xs leading-5 text-slate-500">Isi metrik yang tersedia datanya. Baseline 0 diperbolehkan; persentase perubahan akan ditandai tidak dapat dihitung jika baseline 0.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{feed.metrics.map(m=><label key={m.code} className="rounded-xl bg-slate-50 p-3 text-sm"><span className="font-medium">{m.name}</span><span className="ml-1 text-xs text-slate-500">({m.unit}; lebih baik {m.direction==='UP_IS_BETTER'?'naik':'turun'})</span><input disabled={feed.activity.status!=='OPEN'} type="number" step="any" value={baselines[m.code]||''} onChange={e=>setBaselines(v=>({...v,[m.code]:e.target.value}))} placeholder="Belum diisi" className="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2"/></label>)}</div></div>
   <button disabled={busy||feed.activity.status!=='OPEN'||!valid} onClick={submit} className="w-full rounded-xl bg-navy px-4 py-3 font-semibold text-white disabled:opacity-40">{busy?'Menyimpan…':'Aktifkan 30-Day Plan'}</button>
   {feed.plan&&<div className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">Review: D+7 <b>{new Date(feed.plan.reviewD7).toLocaleDateString('id-ID')}</b> · D+14 <b>{new Date(feed.plan.reviewD14).toLocaleDateString('id-ID')}</b> · D+30 <b>{new Date(feed.plan.reviewD30).toLocaleDateString('id-ID')}</b></div>}
   {msg&&<div className="rounded-xl bg-slate-50 p-3 text-sm text-slate-600">{msg}</div>}
 </div>
}
