'use client';
import { FormEvent, useEffect, useState } from 'react';

type Tenant={id:string;name:string;slug:string;retentionDays:number|null;isActive:boolean};
export default function TenantAdminClient(){
 const [tenants,setTenants]=useState<Tenant[]>([]);const [msg,setMsg]=useState('');const [loading,setLoading]=useState(false);
 async function load(){const r=await fetch('/api/tenants',{cache:'no-store'});const d=await r.json();if(r.ok)setTenants(d.tenants||[]);else setMsg(d.error||'Gagal memuat tenant');}
 useEffect(()=>{void load()},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setMsg('');const fd=new FormData(e.currentTarget);const body={name:fd.get('name'),slug:fd.get('slug'),retentionDays:fd.get('retentionDays')?Number(fd.get('retentionDays')):null,programAdminName:fd.get('programAdminName')||null,programAdminEmail:fd.get('programAdminEmail')||null};const r=await fetch('/api/tenants',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json();setLoading(false);if(!r.ok){setMsg(d.error||'Gagal membuat tenant');return;}e.currentTarget.reset();setMsg(d.devActivationLink?`Tenant berhasil dibuat. Dev activation: ${d.devActivationLink}`:'Tenant berhasil dibuat.');await load();}
 return <div className="grid gap-6 lg:grid-cols-[360px_1fr]"><form onSubmit={submit} className="h-fit space-y-4 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-xl font-semibold">Bank baru</h2><label className="block"><span className="text-sm font-medium">Nama bank</span><input name="name" required className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><label className="block"><span className="text-sm font-medium">Slug</span><input name="slug" required pattern="[a-z0-9]+(-[a-z0-9]+)*" placeholder="bank-contoh" className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><label className="block"><span className="text-sm font-medium">Retensi data (hari)</span><input name="retentionDays" type="number" min="30" max="3650" placeholder="730" className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><div className="border-t border-slate-200 pt-4"><div className="mb-3 text-sm font-semibold">Program Admin awal (opsional)</div><label className="block"><span className="text-sm font-medium">Nama</span><input name="programAdminName" className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><label className="mt-3 block"><span className="text-sm font-medium">Email</span><input name="programAdminEmail" type="email" className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label></div><button disabled={loading} className="w-full rounded-xl bg-navy px-4 py-3 font-semibold text-white disabled:opacity-50">{loading?'Menyimpan…':'Buat tenant'}</button>{msg&&<p className="text-sm text-slate-600">{msg}</p>}</form><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-200 px-5 py-4"><h2 className="text-xl font-semibold">Tenant terdaftar</h2></div><div className="divide-y divide-slate-100">{tenants.map(t=><div key={t.id} className="p-5"><div className="font-semibold">{t.name}</div><div className="mt-1 text-sm text-slate-500">{t.slug} · retensi {t.retentionDays??'belum diatur'} hari · {t.isActive?'aktif':'nonaktif'}</div></div>)}{tenants.length===0&&<p className="p-5 text-sm text-slate-500">Belum ada tenant.</p>}</div></div></div>
}
