'use client';
import { FormEvent, useEffect, useState } from 'react';

type Staff={id:string;role:string;user:{id:string;email:string;name:string;emailVerifiedAt:string|null;mfaEnabled:boolean;isActive:boolean}};
export default function StaffClient({batchId}:{batchId:string}){
 const[staff,setStaff]=useState<Staff[]>([]);const[msg,setMsg]=useState('');const[loading,setLoading]=useState(false);const[activation,setActivation]=useState('');
 async function load(){const r=await fetch(`/api/batches/${batchId}/staff`,{cache:'no-store'});const d=await r.json();if(r.ok)setStaff(d.staff||[]);else setMsg(d.error||'Gagal memuat tim fasilitasi')}
 useEffect(()=>{load()},[batchId]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setMsg('');setActivation('');const fd=new FormData(e.currentTarget);const r=await fetch(`/api/batches/${batchId}/staff`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:fd.get('email'),name:fd.get('name'),role:fd.get('role')})});const d=await r.json();setLoading(false);if(!r.ok){setMsg(d.error||'Gagal menambahkan user');return;}if(d.devActivationLink)setActivation(d.devActivationLink);(e.currentTarget as HTMLFormElement).reset();await load();}
 return <div className="grid gap-5 lg:grid-cols-[380px_1fr]"><form onSubmit={submit} className="h-fit space-y-4 rounded-2xl border border-slate-200 bg-white p-5"><div><h2 className="text-xl font-semibold">Tambahkan tim</h2><p className="mt-1 text-sm text-slate-500">Lead Trainer wajib MFA saat login. Observer dapat dinetapkan ke tim pada Trainer Console.</p></div><label className="block text-sm font-medium">Nama<input name="name" required className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><label className="block text-sm font-medium">Email<input name="email" type="email" required className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><label className="block text-sm font-medium">Role<select name="role" required className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="LEAD_TRAINER">Lead Trainer</option><option value="CO_FACILITATOR">Co-Facilitator / Observer</option><option value="SPONSOR_VIEWER">Sponsor / Management Viewer</option></select></label>{msg&&<div className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900">{msg}</div>}{activation&&<div className="rounded-xl bg-slate-50 p-3 text-xs text-slate-600"><b>Dev activation link:</b><div className="mt-1 break-all font-mono">{activation}</div></div>}<button disabled={loading} className="w-full rounded-xl bg-navy px-4 py-3 font-semibold text-white disabled:opacity-50">{loading?'Menyimpan…':'Tambahkan'}</button></form><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-xl font-semibold">Tim batch</h2><div className="mt-4 space-y-3">{staff.length===0?<p className="text-sm text-slate-500">Belum ada tim fasilitasi.</p>:staff.map(s=><div key={s.id} className="flex flex-col gap-2 rounded-xl bg-slate-50 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="font-semibold">{s.user.name}</div><div className="text-sm text-slate-500">{s.user.email}</div></div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-white px-2.5 py-1 text-xs font-semibold ring-1 ring-slate-200">{s.role}</span>{s.role==='LEAD_TRAINER'&&<span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${s.user.mfaEnabled?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-800'}`}>{s.user.mfaEnabled?'MFA aktif':'MFA belum aktif'}</span>}</div></div>)}</div></section></div>
}
