import ExcelJS from 'exceljs';
import { prisma } from '@ltw/db';
import { assertPermission } from '@/lib/auth';
import { jsonError } from '@/lib/http';

function json(value:unknown){return value===null||value===undefined?'':JSON.stringify(value);}
function style(ws:ExcelJS.Worksheet){
  ws.views=[{state:'frozen',ySplit:1}];
  ws.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};
  ws.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF10243E'}};
  ws.getRow(1).alignment={vertical:'middle',wrapText:true};
  ws.getRow(1).height=24;
  ws.eachRow((row,n)=>{if(n>1)row.alignment={vertical:'top',wrapText:true};});
}

export async function GET(){
  try{
    const actor=await assertPermission('CONTENT_MANAGE',{});
    const [items,rubrics,tests]=await Promise.all([
      prisma.contentItem.findMany({
        where:{tenantId:null},
        orderBy:[{code:'asc'},{version:'asc'}],
        select:{code:true,type:true,version:true,title:true,payload:true,answerKey:true,isPublished:true,createdAt:true},
      }),
      prisma.rubric.findMany({
        where:{tenantId:null},
        orderBy:[{code:'asc'},{version:'asc'}],
        select:{code:true,version:true,name:true,dimensions:true,isPublished:true},
      }),
      prisma.test.findMany({
        where:{tenantId:null},
        orderBy:[{code:'asc'},{version:'asc'}],
        include:{questions:{orderBy:{sequence:'asc'}}},
      }),
    ]);

    const wb=new ExcelJS.Workbook();
    wb.creator='Leadership That Works';
    wb.created=new Date();

    const meta=wb.addWorksheet('README');
    meta.addRows([
      ['Leadership That Works - Master Content Export'],
      ['Generated At',new Date().toISOString()],
      ['Generated By',actor.email],
      ['Import Safety','Use the same sheet names and column headers. JSON columns must contain valid JSON.'],
      ['Scope','Global master content only (tenantId = null).'],
    ]);
    meta.getColumn(1).width=28;meta.getColumn(2).width=90;

    const contentWs=wb.addWorksheet('Content Items');
    contentWs.columns=[
      {header:'Code',key:'code',width:34},{header:'Type',key:'type',width:24},{header:'Version',key:'version',width:10},
      {header:'Title',key:'title',width:42},{header:'IsPublished',key:'published',width:13},
      {header:'PayloadJSON',key:'payload',width:80},{header:'AnswerKeyJSON',key:'answer',width:80},
    ];
    for(const item of items)contentWs.addRow({
      code:item.code,type:item.type,version:item.version,title:item.title,published:item.isPublished,
      payload:json(item.payload),answer:json(item.answerKey),
    });
    style(contentWs);

    const rubricWs=wb.addWorksheet('Rubrics');
    rubricWs.columns=[
      {header:'Code',key:'code',width:28},{header:'Version',key:'version',width:10},{header:'Name',key:'name',width:36},
      {header:'IsPublished',key:'published',width:13},{header:'DimensionsJSON',key:'dimensions',width:90},
    ];
    for(const rubric of rubrics)rubricWs.addRow({
      code:rubric.code,version:rubric.version,name:rubric.name,published:rubric.isPublished,dimensions:json(rubric.dimensions),
    });
    style(rubricWs);

    const testWs=wb.addWorksheet('Test Questions');
    testWs.columns=[
      {header:'TestCode',key:'testCode',width:24},{header:'TestVersion',key:'testVersion',width:12},{header:'TestName',key:'testName',width:40},
      {header:'DurationSec',key:'duration',width:14},{header:'QuestionCode',key:'questionCode',width:16},{header:'Sequence',key:'sequence',width:10},
      {header:'Prompt',key:'prompt',width:65},{header:'OptionsJSON',key:'options',width:70},{header:'AnswerKey',key:'answer',width:12},
      {header:'Explanation',key:'explanation',width:60},{header:'Points',key:'points',width:10},
    ];
    for(const test of tests)for(const q of test.questions)testWs.addRow({
      testCode:test.code,testVersion:test.version,testName:test.name,duration:test.durationSec??'',
      questionCode:q.code,sequence:q.sequence,prompt:q.prompt,options:json(q.options),answer:q.answerKey,
      explanation:q.explanation??'',points:q.points,
    });
    style(testWs);

    const bytes=await wb.xlsx.writeBuffer();
    return new Response(new Uint8Array(bytes),{
      headers:{
        'content-type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'content-disposition':'attachment; filename="Leadership_Master_Content.xlsx"',
        'cache-control':'no-store',
      },
    });
  }catch(e){return jsonError(e)}
}
